import EmberRouter from '@ember/routing/router';
import config from 'dummy/config/environment';

export default class Router extends EmberRouter {
  location = config.locationType;
  rootURL = config.rootURL;
}

Router.map(function () {
  // ember-cli-addon-docs
  this.route('docs', function () {
    // docs homepage (required)
    this.route('configuration'); // docs subpage
    this.route('usage'); // docs subpage
    this.route('api', function () {
      // autogenerated API homepage (required)
      this.route('item', { path: '/*path' }); // autogenerated API subpages (required)
    });
  });

  // dummy app
  this.route('client-server-one', {});
  this.route('client-server-two', {}, function () {
    this.route('example', {});
  });
  this.route('demo', {});

  // 404
  this.route('not-found', { path: '/*path' });
});
