name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint

  build-windows:
    runs-on: windows-latest
    needs: lint
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        browser: [
          'ie'
        ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn test:ember --host 127.0.0.1 --launch ${{ matrix.browser }}

  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]
        node: ["12", "14", "16"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn test:ember --launch ${{ matrix.browser }}

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install --no-lockfile --non-interactive
    - name: Test
      run: yarn test:ember --launch ${{ matrix.browser }}

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: ${{ matrix.allow-failure }}
    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario: [
          ember-lts-3.20,
          ember-lts-3.24,
          ember-release,
          ember-beta,
          ember-default-with-jquery,
          ember-classic,
          embroider-safe,
          embroider-optimized
        ]
        allow-failure: [false]
        include:
          - ember-try-scenario: ember-canary
            allow-failure: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
